const form=document.querySelector('#generator'),prompt=document.querySelector('#prompt'),ratio=document.querySelector('#ratio'),list=document.querySelector('#projectList'),toast=document.querySelector('#toast');
const owner=localStorage.getItem('bidvid-owner')||(crypto.randomUUID?crypto.randomUUID():`visitor-${Date.now()}-${Math.random().toString(36).slice(2)}`);localStorage.setItem('bidvid-owner',owner);
function notify(message){toast.textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2800)}
function safeText(text){const node=document.createElement('span');node.textContent=text;return node.innerHTML}
function renderProjects(projects){if(!projects.length){list.innerHTML='<article class="empty"><i>✦</i><h3>Your next video starts here</h3><p>Use the generator above to create your first project.</p></article>';return}list.innerHTML=projects.map(project=>`<article class="project"><div class="thumb">${project.status==='ready'?'▶ Your video is ready':'✦ Generating your vision'}</div><h3>${safeText(project.prompt.length>48?`${project.prompt.slice(0,48)}…`:project.prompt)}</h3><p>${project.ratio} · ${project.status==='ready'?'Ready to review':'Processing'}</p></article>`).join('')}
async function loadProjects(){try{const response=await fetch(`/api/projects?owner=${encodeURIComponent(owner)}`),data=await response.json();if(response.ok)renderProjects(data.projects)}catch{notify('Could not connect to the server.')}}
form.addEventListener('submit',async event=>{event.preventDefault();const text=prompt.value.trim();if(!text){prompt.focus();return notify('Describe the video you would like to create.')}const button=form.querySelector('.generate');button.disabled=true;button.textContent='Creating…';try{const response=await fetch('/api/projects',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({owner,prompt:text,ratio:ratio.value})}),data=await response.json();if(!response.ok)throw new Error(data.error);prompt.value='';notify('Your video project is being created.');await loadProjects();document.querySelector('#library').scrollIntoView({behavior:'smooth'});setTimeout(loadProjects,3500)}catch(error){notify(error.message||'Could not create the project.')}finally{button.disabled=false;button.innerHTML='✦ Generate'}});
document.querySelectorAll('[data-prompt]').forEach(button=>button.addEventListener('click',()=>{prompt.value=button.dataset.prompt;prompt.focus();document.querySelector('#studio').scrollIntoView({behavior:'smooth'})}));document.querySelector('#newProject').addEventListener('click',()=>{prompt.value='';prompt.focus();window.scrollTo({top:0,behavior:'smooth'})});document.querySelector('#seeAll').addEventListener('click',()=>notify('More templates are coming soon.'));loadProjects();

